CREATE TABLE REFRESH_TOKEN_WHITELIST(
    USER_AGENT VARCHAR(300) NOT NULL,
    USERNAME VARCHAR(40) NOT NULL,
    REFRESH_TOKEN VARCHAR NOT NULL,
    CONSTRAINT PRIMARY_KEY_RTW_ID PRIMARY KEY (USERNAME, USER_AGENT)
);