CREATE TABLE AUTH_TOKEN(
    CLIENT_ID UUID PRIMARY KEY NOT NULL,
    ACCESS_TOKEN VARCHAR NOT NULL,
    REFRESH_TOKEN VARCHAR NOT NULL,
    ACCESS_TOKEN_EXPIRATION_TIME TIMESTAMP NOT NULL,
    REFRESH_TOKEN_EXPIRATION_TIME TIMESTAMP NOT NULL
);