CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE REFRESH_TOKEN_WHITELIST(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    USER_AGENT VARCHAR(300) NOT NULL,
    USERNAME VARCHAR(40) NOT NULL,
    REFRESH_TOKEN VARCHAR NOT NULL,
    CONSTRAINT PRIMARY_KEY_RTW_ID PRIMARY KEY (ID)
);