CREATE TABLE AUTH_ROLE_TO_USERNAME(
    USERNAME VARCHAR(40) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    CONSTRAINT PRIMARY_KEY_ARTU_USERNAME PRIMARY KEY (USERNAME),
    CONSTRAINT FOREIGN_KEY_ROLE FOREIGN KEY (ROLE) REFERENCES AUTH_ROLE (ROLE) ON DELETE CASCADE
);

INSERT INTO AUTH_ROLE_TO_USERNAME(USERNAME, ROLE) VALUES ('username', 'ROLE_FREE_USER');
