CREATE TABLE AUTH_ROLE_TO_USERNAME(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    USERNAME VARCHAR(40) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    ROLE_ID UUID NOT NULL,
    CONSTRAINT PRIMARY_KEY_ARTU_ID PRIMARY KEY (ID),
    CONSTRAINT FOREIGN_KEY_ARTU_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES AUTH_ROLE (ID) ON DELETE CASCADE
);

INSERT INTO AUTH_ROLE_TO_USERNAME(USERNAME, ROLE, ROLE_ID) VALUES ('username', 'ROLE_FREE_USER', 'b7134137-7cea-4b10-af4a-ce90b78bac16');
