CREATE TABLE AUTH_ROLE_TO_AUTHORITIES(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    ROLE VARCHAR(20) NOT NULL,
    ROLE_ID UUID NOT NULL,
    AUTHORITIES VARCHAR NOT NULL,
    CONSTRAINT PRIMARY_KEY_ARTA_ID PRIMARY KEY (ID),
    CONSTRAINT FOREIGN_KEY_ARTA_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES AUTH_ROLE (ID) ON DELETE CASCADE
);

INSERT INTO AUTH_ROLE_TO_AUTHORITIES(ROLE, ROLE_ID, AUTHORITIES) VALUES ('ROLE_FREE_USER', 'b7134137-7cea-4b10-af4a-ce90b78bac16', 'REFRESH_TOKEN_DELETE REFRESH_TOKEN_ALL_DELETE');
