server:
  port: 8900

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/authorizationdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver