server:
  port: 8900
spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://kitkat-authorization-database:5432/authorizationdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver